const UserAction = {
  RECEIVE_CURRENT_USER: "RECEIVE_CURRENT_USER",
  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  LOGOUT_USER: "LOGOUT_USER",
  RECEIVE_ERRORS: "RECEIVE_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};

export default UserAction;
